name: Deploy React App to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}


on:
  pull_request_target:
    types: [opened, synchronize]
    branches:
      - main  # Set your default branch here
jobs:
  deploy-web:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
          node-version-file: 'package.json'
    - name: Install dependencies
      run: |
          npm install --global vercel@latest
          npm install --global pnpm
    
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=prod --token="${{ secrets.VERCEL_TOKEN }}"
    
    - name: Run pnpm install
      run: pnpm install
      
    - name: Build the project
      run: npm run build
      
    - name: Build Project Artifacts
      run: vercel build --token="${{ secrets.VERCEL_TOKEN }}"
      
    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |
        npm install -g vercel
        vercel --prod --confirm --token $VERCEL_TOKEN
